.\" Manpage for sandmap.
.\" Contact trimstray@gmail.com.
.TH man 8 "14.03.2018" "1.2.0" "sandmap man page"
.SH NAME
Sandmap \- supporting network and system reconnaissance
.SH SYNOPSIS
sandmap <option|long-option>
.SH DESCRIPTION
A tool supporting network and system reconnaissance using the massive Nmap engine. It provides a user-friendly interface, automates and speeds up scanning, and allows you to easily use many advanced scanning techniques.
.SH OPTIONS
--help
        show this message

--debug
        displays information on the screen (debug mode)

--verbose
        displays 'info' messages on the screen (verbose mode)

--time
        displays execution time, occurs only with --verbose

-c, --config <file>
        attach an external config file to the script
.SH SEE ALSO
https://github.com/trimstray/sandmap
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (trimstray@gmail.com)
