#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: cli_help()
#
# Description:
#   Show help in cli.
#
# Usage:
#   cli_help
#
# Examples:
#   cli_help
#

function cli_help() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="cli_help"
  local _STATE=0

  printf "%s" "
  Main Commands
  -------------

    help <key>            show this message, key optional
    show <key>            show info about all modules, key optional
    config <opt>          show global configuration
    set [opt]             set key value
    use <key>             set current module

    reload                reload all modules
    banner                show banner

    Options:

      <key>               module name
      [opt]               opt name

  Module Commands
  ---------------

    help                  display module help
    show                  display module info
    config                display module configuration
    set                   set key value

  Examples
  --------

    show
    sample                enable 'sample' module
    config sample         show 'sample' module configuration

"

  return $_STATE

}
