#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: cli_distributor()
#
# Description:
#   Modules distributor.
#
# Usage:
#   cli_distributor
#
# Examples:
#   cli_distributor
#

function cli_distributor() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="cli_distributor"
  local _STATE=0

  local _argv=("$@")

  # shellcheck disable=SC2154
  if [[ "${_argv[0]}" == "help" ]] ; then

    if [[ "${_fin[0]}" -eq 0 ]] && [[ "${_fin[1]}" -eq 0 ]]; then

      if [[ "${#_argv[1]}" -eq 0 ]] ; then

        cli_help

        _fin[0]=0
        _fin[1]=0

      else

        init_module "${_argv[@]}"
        init_help

        _fin[0]=0
        _fin[1]=1

      fi

    elif [[ "${_fin[0]}" -eq 1 ]] && [[ "${_fin[1]}" -eq 1 ]]; then

      init_module "${_argv[@]}"
      init_help

      _fin[0]=1
      _fin[1]=1

    else

      cli_help

      _fin[0]=0
      _fin[1]=0

    fi

  elif [[ "${_argv[0]}" == "show" ]] ; then

    if [[ "${_fin[0]}" -eq 0 ]] && [[ "${_fin[1]}" -eq 0 ]]; then

      if [[ "${#_argv[1]}" -eq 0 ]] ; then

        cli_show

        _fin[0]=0
        _fin[1]=0

      else

        init_module "${_argv[@]}"
        init_show

        _fin[0]=0
        _fin[1]=1

      fi

    elif [[ "${_fin[0]}" -eq 1 ]] && [[ "${_fin[1]}" -eq 1 ]]; then

      init_module "${_argv[@]}"
      init_show

      _fin[0]=1
      _fin[1]=1

    else

      cli_show

      _fin[0]=0
      _fin[1]=0

    fi

  elif [[ "${_argv[0]}" == "config" ]] ; then

    if [[ "${_fin[0]}" -eq 0 ]] && [[ "${_fin[1]}" -eq 0 ]]; then

      if [[ "${#_argv[1]}" -eq 0 ]] ; then

        cli_config
        show_config

        _fin[0]=0
        _fin[1]=0

      else

        init_module "${_argv[@]}"
        init_config
        show_config

        _fin[0]=0
        _fin[1]=1

      fi

    elif [[ "${_fin[0]}" -eq 1 ]] && [[ "${_fin[1]}" -eq 1 ]]; then

      init_module "${_argv[@]}"
      init_config
      show_config

      _fin[0]=1
      _fin[1]=1

    else

      cli_config
      show_config

      _fin[0]=0
      _fin[1]=0

    fi

  elif [[ "${_argv[0]}" == "reload" ]] ; then

    if [[ "${_fin[0]}" -eq 0 ]] && [[ "${_fin[1]}" -eq 0 ]]; then

      # shellcheck disable=SC2034
      modules_list=()
      # shellcheck disable=SC2034
      modules_full_list=()
      # ReInitialize modules.
      load_modules

      printf "stdout: %s\n" "modules reloaded"

    fi

  else

    # shellcheck disable=SC2034
    if (( $(echo "${_argv[@]}" | grep -o "$_fname" | wc -w) == 1 )); then

      _fin[0]=1
      _fin[1]=1

      # shellcheck disable=SC2034
      _ld_module="$_fname"

      init_module "$_ld_module"

      "$_ld_module"

      # shellcheck disable=SC2034
      __cli_banner="$_fname"

    fi

  fi

  return $_STATE

}
