#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: cli_help()
#
# Description:
#   Show help in cli.
#
# Usage:
#   cli_help
#
# Examples:
#   cli_help
#

function cli_help() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="cli_help"
  local _STATE=0

  printf "%s" "
  CLI Help:

    Main:

      help <key>            show this message, key optional
      show <key>            show info about all modules, key optional
      reload                reload all modules

      Options:

        <key>               module name

    In modules:

      help                  display module help
      show                  display module info

    Examples:

      show
      sample                enable sample module

"

  return $_STATE

}
