#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: cli_show()
#
# Description:
#   Show help in cli.
#
# Usage:
#   cli_show
#
# Examples:
#   cli_show
#

function cli_show() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="cli_show"
  local _STATE=0

  # shellcheck disable=SC2154
  _modules_count=$(find "${_modules}" -name '*.mod' | wc -l)

  printf "\n  %s: \e[5;33m%s\e[m\n" \
         "Modules" "$_modules_count"

  printf "\n  %s\n\n" "Available:"

  # shellcheck disable=SC2154
  for i in "${modules_full_list[@]}" ; do

    # shellcheck disable=SC2034
    _fname=$(echo "$i" | awk -v FS="(:|:)" '{print $1}')
    # shellcheck disable=SC2034
    _fpath=$(echo "$i" | awk -v FS="(:|:)" '{print $2}')

    printf "   * \e[1;38m%s\e[m (file: \e[2;37m%s\e[m)\n" "$_fname" "$_fpath"

  done

  echo

  return $_STATE

}
