#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: cli_config()
#
# Description:
#   Show help in cli.
#
# Usage:
#   cli_config
#
# Examples:
#   cli_config
#

function cli_config() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="cli_config"
  local _STATE=0

  # shellcheck disable=SC2034,SC2154
  _config_file="${_cfg}/config.cfg"

  if [[ -e "$_config_file" ]] ; then

    # shellcheck disable=SC1090
    source "$_config_file"

  fi

  return $_STATE

}
