#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: cli_help()
#
# Description:
#   Show help in cli.
#
# Usage:
#   cli_help
#
# Examples:
#   cli_help
#

function cli_help() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="cli_help"
  local _STATE=0

  printf "%s" "
  Main Commands
  -------------

    help    <module>              show cli help or module help
    show    <module>              show info about modules or module
    config  <key>|<module [key]>  show global or module configuration
    set     <key>|<module [key]>  set global or module variable value
    use     <module>              use module (changed env)

    reload  <modules|config>      reload all modules cache or configuration
    banner                        show banner

    Options:

      <module>                    module name
      <key>                       key value

  Module Commands
  ---------------

    help                          display module help
    show                          display module info
    config  <key>                 show module configuration
    set     <key>                 set module variable value

  Examples
  --------

    show sample                   show 'sample' module info
    config terminal               show 'terminal' key value
    use sample                    use 'sample' module

"

  return $_STATE

}
