#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_config()
#
# Description:
#   Init configuration file.
#
# Usage:
#   init_config
#
# Examples:
#   init_config
#

function init_config() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_config"
  local _STATE=0

  # shellcheck disable=SC2034
  # _session_variables=("${_module_params[@]}")

  return $_STATE

}
