#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_module()
#
# Description:
#   Init modules.
#
# Usage:
#   init_module
#
# Examples:
#   init_module
#

function init_module() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_module"
  local _STATE=0

  # shellcheck disable=SC2154
  _modules="${_rel}/modules"

  local _argv=("$@")

  local _mod="${_modules}/${_argv[0]}.mod"

  if [[ -e "${_mod}" ]] ; then

    # shellcheck disable=SC1090
    source "${_mod}"

  else

    printf "stdout: %s\n" "unknown command"

  fi

  return $_STATE

}
