#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_module()
#
# Description:
#   Load modules.
#
# Usage:
#   init_module
#
# Examples:
#   init_module
#

function init_module() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_module"
  local _STATE=0

  # shellcheck disable=SC2154
  _modules="${_rel}/modules"

  _argv=("$@")

  local _mod="${_modules}/${_argv[0]}.mod"

  if [[ -e "${_mod}" ]] ; then

    # shellcheck disable=SC1090
    source "${_mod}"

    # Run module:
    ${_argv[0]}

  else

    printf "stdout: %s\n" "unknown command"

  fi

  return $_STATE

}
