#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_config()
#
# Description:
#   Init configuration file.
#
# Usage:
#   init_config
#
# Examples:
#   init_config
#

function init_config() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_config"
  local _STATE=0

  export _session_variables=(\
  "IP address:ipaddr:$ipaddr" \
  "Service port number:port:$port" \
  "Network interface:iface:$iface" \
  "MAC address:hwaddr:$hwaddr" \
  "Domain name:domain:$domain" \
  "Report type:report:$report" \
  "Pass through TOR:tor:$tor" \
  "Terminal type:terminal:$terminal")

  return $_STATE

}
