#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_search()
#
# Description:
#   Init search module.
#
# Usage:
#   init_search
#
# Examples:
#   init_search
#

function init_search() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_search"
  local _STATE=0

  local _spattern="$1"

  _cr="-40.40"

  printf "\n  \e[1;38m%-15.15s %${_cr}s %s\e[m\n  %-15.15s %${_cr}s %s\n\n" \
         "Module" \
         "Alias" \
         "Nmap Parameters" \
         "------" \
         "-----" \
         "---------------"

  # shellcheck disable=SC2154
  for _svar in "${_profiles_list[@]}" ; do

    # shellcheck disable=SC2034
    _key_alias=$(echo "$_svar" | awk -v FS="(;|;)" '{print $1}')
    # shellcheck disable=SC2034
    _key_cmd=$(echo "$_svar" | awk -v FS="(;|;)" '{print $2}')
    # shellcheck disable=SC2034
    _key_mod=$(echo "$_svar" | awk -v FS="(;|;)" '{print $3}')

    if [[ "$_key_alias" == *"$_spattern"* ]] ; then

      printf "  \e[1;32m%-15.15s\e[m \e[1;36m%${_cr}s\e[m %s\n" \
             "$_key_mod" \
             "$_key_alias" \
             "$_key_cmd"

    fi

  done

  echo

  unset _svar

  return $_STATE

}
