#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_show()
#
# Description:
#   Show help in cli.
#
# Usage:
#   init_show
#
# Examples:
#   init_show
#

function init_show() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_show"
  local _STATE=0



  return $_STATE

}
