#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_distributor()
#
# Description:
#   Modules distributor.
#
# Usage:
#   init_distributor
#
# Examples:
#   init_distributor
#

function init_distributor() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_distributor"
  local _STATE=0

  local _argv=("$@")

  # shellcheck disable=SC2154
  if [[ "${_argv[0]}" == "help" ]] ; then

    if [[ "$__cli_level" -eq 0 ]] ; then

      init_help

    else

      true

    fi

  elif [[ "${_argv[0]}" == "show" ]] ; then

    if [[ "$__cli_level" -eq 0 ]] ; then

      init_show

    else

      true

    fi

  fi

  return $_STATE

}
