#!/usr/bin/env bash

# shellcheck shell=bash

readonly __cli_prompt="cli"
# shellcheck disable=SC2034
__cli_banner="main"
# shellcheck disable=SC2034
__cli_level=0

_motd_status=0

readonly _und=$(tput smul)
readonly _nound=$(tput rmul)
readonly _bold=$(tput bold)
readonly _normal=$(tput sgr0)


# ``````````````````````````````````````````````````````````````````````````````
# Function name: motd_cli()
#
# Description:
#   Message of the day.
#
# Usage:
#   motd_cli
#
# Examples:
#   motd_cli
#

function motd_cli() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="motd_cli"
  local _STATE=0

  printf "${_bold}\e[2;31m\n\n\n%s\e[m${_normal}" "
     (        )
     O        O
     ()      ()
      Oo.nn.oO
       _mmmm_
     \/_mmmm_\/
     \/_mmmm_\/
     \/ mmmm \/
         nn
         nn
         ()
          ()    /
           ()__()
            '--'"

  tput cup 1 21 ; printf "%s" " _______                 __"
  tput cup 2 21 ; printf "%s" "|     __|.---.-.-----.--|  |.--------.---.-.-----."
  tput cup 3 21 ; printf "%s" "|__     ||  _  |     |  _  ||        |  _  |  _  |"
  tput cup 4 21 ; printf "%s" "|_______||___._|__|__|_____||__|__|__|___._|   __|"
  tput cup 5 64 ; printf "%s" "|__|"

  tput cup 6 38 ; printf "%s: \e[3;36m%s\e[m" "Author" "trimstray"
  tput cup 6 57 ; printf "%s: \e[3;36m%s\e[m" "Version" "1.0.0"

  tput cup 8 24 ; printf "%s \e[1;38m%s\e[m" "Project:" "https://github.com/trimstray/sandmap"

  tput cup 10 24 ; printf "%s" "This program comes with ABSOLUTELY NO WARRANTY."
  tput cup 11 24 ; printf "%s" "This is free software, and you are welcome to redistribute it"
  tput cup 12 24 ; printf "%s" "under certain conditions; for more details please see"
  tput cup 13 24 ; printf "%s" "<http://www.gnu.org/licenses/>."

  tput cup 15 24 ; printf "%s" "Hint:"
  tput cup 17 26 ; printf "%s '${_und}\e[1;38m%s\e[m${_normal}' %s" \
                          "Try" "help" "to show all cli commands and start!"
  tput cup 20 0

  return $_STATE

}

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_cli()
#
# Description:
#   Init sandmap cli.
#
# Usage:
#   init_cli
#
# Examples:
#   init_cli
#

function init_cli() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_cli"
  local _STATE=0

  clear

  if [[ "$_motd_status" -eq 0 ]] ; then

    motd_cli
    _motd_status=1

  fi

  local input_array=()

  while [[ "${input_array[0]}" != "exit" ]] ; do

    cstate="1"

    # shellcheck disable=SC2154
    printf "\e[1;38m%s\e[m(\e[0;38m%s\e[m)\e[4;32m>\e[m " "${__cli_prompt}" "${__cli_banner}" && read -ra input_array

    case ${input_array[0]} in

      clear)

        init_cli
        cstate="0" ;;

      main)

        # shellcheck disable=SC2034
        __cli_banner="main"
        # shellcheck disable=SC2034
        __cli_level=0

        init_cli
        cstate="0" ;;

      exit)

        _exit_ 0 ;;

      "")

        echo -en ""
        cstate="0" ;;

      *)

        init_distributor "${input_array[@]}"
        # shellcheck disable=SC2034
        cstate="0"

      ;;

    esac

  done

  return $_STATE

}
