#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_help()
#
# Description:
#   Show help in cli.
#
# Usage:
#   init_help
#
# Examples:
#   init_help
#

function init_help() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_help"
  local _STATE=0

  printf "%s" "
  CLI Help:

    show <key>            show key info
    <module> <info|help>  show key info about module

    Options:

      <key> - modules     displays modules information

    Examples:
      show modules
      sample info

"

  return $_STATE

}
