#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_help()
#
# Description:
#   Show help in cli.
#
# Usage:
#   init_help
#
# Examples:
#   init_help
#

function init_help() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_help"
  local _STATE=0

  # shellcheck disable=SC2154
  printf "%s\n\n" "${_module_opts[1]}"

  return $_STATE

}
