#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_config()
#
# Description:
#   Init configuration file.
#
# Usage:
#   init_config
#
# Examples:
#   init_config
#

function init_config() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_config"
  local _STATE=0

  export _session_variables=(\
  "Destination;'127.0.0.1,example.com';dst;$dst" \
  "Service port number;'T:20-110';port;$port" \
  "Network interface;'eth0';iface;$iface" \
  "MAC address;'fe:54:00:fe:7f:00';hwaddr;$hwaddr" \
  "Report type;'nmap|xml|grep';report;$report" \
  "Pass through TOR;'true|false';tor;$tor" \
  "Terminal type;'internal|external';terminal;$terminal")

  return $_STATE

}
