#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: init_show()
#
# Description:
#   Show help in cli.
#
# Usage:
#   init_show
#
# Examples:
#   init_show
#

function init_show() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="init_show"
  local _STATE=0

  local _marg="$1"

  _count=0

  printf "\n  \e[1;38m%-4.4s %-35.35s %s\e[m\n  %-4.4s %-35.35s %s\n\n" \
         "ID" \
         "Alias" \
         "Nmap Parameters" \
         "--" \
         "-----" \
         "---------------"

  # shellcheck disable=SC2034,SC2154
  for _svar in "${_module_commands[@]}" ; do

    # shellcheck disable=SC2034
    _key_desc=$(echo "$_svar" | awk -v FS="(;|;)" '{print $1}')
    # shellcheck disable=SC2034
    _key_comm=$(echo "$_svar" | awk -v FS="(;|;)" '{print $2}')
    # shellcheck disable=SC2034
    _key_alias=$(echo "$_svar" | awk -v FS="(;|;)" '{print $3}')
    # shellcheck disable=SC2034
    _key_cmd=$(echo "$_svar" | awk -v FS="(;|;)" '{print $4}')

    if [[ "$_key_alias" == "$_marg" ]] ; then

      printf "  \e[1;32m%-4.4s\e[m \e[1;36m%-35.35s\e[m %s\n" \
             "$_count" \
             "$_key_alias" \
             "$_key_cmd"

    elif [[ -z "$_marg" ]] ; then

      printf "  \e[1;32m%-4.4s\e[m \e[1;36m%-35.35s\e[m %s\n" \
             "$_count" \
             "$_key_alias" \
             "$_key_cmd"

    fi

    _count=$((_count + 1))

  done

  echo

  return $_STATE

}
