#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: module_show()
#
# Description:
#   Show help in cli.
#
# Usage:
#   module_show
#
# Examples:
#   module_show
#

function module_show() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="module_show"
  local _STATE=0

  local _marg="$1"

  _count=0

  _cr="-35.35"

  # shellcheck disable=SC2034,SC2154
  _static_menu="${_tmp}/.static.menu"

  : >"${_static_menu}"

  if [[ -z "$_marg" ]] ; then

    printf "\\n    \\e[1;38m%-4.4s %${_cr}s %s\\e[m\\n    %-4.4s %${_cr}s %s\\n\\n" \
           "ID" \
           "Alias" \
           "Nmap Parameters" \
           "--" \
           "-----" \
           "---------------" >> "${_static_menu}"

  fi

  # shellcheck disable=SC2034,SC2154
  for _svar in "${_module_commands[@]}" ; do

    # shellcheck disable=SC2034
    _key_desc=$(echo "$_svar" | awk -v FS="(;|;)" '{print $1}')
    # shellcheck disable=SC2034
    _key_comm=$(echo "$_svar" | awk -v FS="(;|;)" '{print $2}')
    # shellcheck disable=SC2034
    _key_alias=$(echo "$_svar" | awk -v FS="(;|;)" '{print $3}')
    # shellcheck disable=SC2034
    _key_cmd=$(echo "$_svar" | awk -v FS="(;|;)" '{print $4}')

    if [[ "$_key_alias" == "$_marg" ]] ; then

      printf "\\n    \\e[1;38m%-4.4s %${_cr}s %s\\e[m\\n    %-4.4s %${_cr}s %s\\n\\n" \
             "ID" \
             "Alias" \
             "Nmap Parameters" \
             "--" \
             "-----" \
             "---------------" >> "${_static_menu}"

      printf "    \\e[1;32m%-4.4s\\e[m \\e[1;34m%${_cr}s\\e[m %s\\n" \
             "$_count" \
             "$_key_alias" \
             "$_key_cmd" >> "${_static_menu}"

    elif [[ -z "$_marg" ]] ; then

      printf "    \\e[1;32m%-4.4s\\e[m \\e[1;34m%${_cr}s\\e[m %s\\n" \
             "$_count" \
             "$_key_alias" \
             "$_key_cmd" >> "${_static_menu}"

    fi

    _count=$((_count + 1))

  done

  cat "${_static_menu}"

  echo

  : >"${_static_menu}"

  return $_STATE

}
