#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: module_help()
#
# Description:
#   Show help in cli.
#
# Usage:
#   module_help
#
# Examples:
#   module_help
#

function module_help() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="module_help"
  local _STATE=0

  # shellcheck disable=SC2154
  printf "%s\n\n" "${_module_help[@]}"

  return $_STATE

}
