#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: module_distributor()
#
# Description:
#   Modules distributor.
#
# Usage:
#   module_distributor
#
# Examples:
#   module_distributor
#

function module_distributor() {

  # shellcheck disable=SC2034
  local _FUNCTION_ID="module_distributor"
  local _STATE=0

  # shellcheck disable=SC2154
  ${input_array[0]}

  return $_STATE

}
