#!/usr/bin/env bash

# shellcheck shell=bash

# ``````````````````````````````````````````````````````````````````````````````
# Function name: show_config()
#
# Description:
#   Show config.
#
# Usage:
#   show_config
#
# Examples:
#   show_config
#

function show_config() {

  local _FUNCTION_ID="show_config"
  local _STATE=0

  local _session_arg="$1"

  export _session_variables=(\
                      "IP address:ipaddr:_ipaddr" \
                      "Service port number:port:_port" \
                      "Username:user:_user" \
                      "User password:pass:_pass" \
                      "Network interface:iface:_iface" \
                      "MAC address:hwaddr:_hwaddr" \
                      "Domain name:domain:_domain" \
                      "Database user name:dbuser:_dbuser" \
                      "Database user password:dbpass:_dbpass" \
                      "Report type:report:_report" \
                      "Pass through TOR:tor:_tor" \
                      "Terminal type:terminal:_terminal")

  # shellcheck disable=SC2154
  for _svar in "${_session_variables[@]}" ; do

    _key_description=$(echo "$_svar" | awk -v FS="(:|:)" '{print $1}')
    _key_id=$(echo "$_svar" | awk -v FS="(:|:)" '{print $2}')
    _key_var=$(echo "$_svar" | awk -v FS="(:|:)" '{print $3}')

    if [[ -z "$_key_id" ]] ; then

      printf "stdout: %s\n" "invalid session param"

    fi

    if [[ "$_key_id" != "web" ]] || [[ "$_key_id" != "db" ]] ; then

      _i="" ; eval _i='$'"$_key_var"

    else

      _i="true"

    fi

    # Show specific key.
    if [[ "$_session_arg" == "$_key_id" ]] ; then

      # Print without key value.
      if [[ -z "$_i" ]] ; then

        printf "\n  Description: %s\n  { \"\e[0;38m%s\e[m\":\"\e[0;36m%s\e[m\" }\n\n" "$_key_description" "$_key_id" ""

      # Print with key value.
      else

        if [[ "$_key_id" == "web" ]] ; then

          printf "\n  Description: %s\n" "$_key_description"

          # shellcheck disable=SC2154
          for i in "${_web_stack[@]}" ; do

            printf "  { \"\e[0;38m%s\e[m\":\"\e[0;36m%s\e[m\" }\n" "$_key_id" "$i"

          done

          printf "\n"

        elif [[ "$_key_id" == "db" ]] ; then

          # shellcheck disable=SC2154
          printf "\n  Description: %s\n" "$_key_description"

          for i in "${_db_stack[@]}" ; do

            printf "  { \"\e[0;38m%s\e[m\":\"\e[0;36m%s\e[m\" }\n" "$_key_id" "$i"

          done

          printf "\n"

        else

          printf "\n  Description: %s\n  { \"\e[0;38m%s\e[m\":\"\e[0;36m%s\e[m\" }\n\n" "$_key_description" "$_key_id" "$_i"

        fi

      fi

    # Show all keys.
    elif [[ -z "$_session_arg" ]] ; then

      # Print without key value.
      if [[ -z "$_i" ]] ; then

        printf "\n  Description: %s\n  { \"\e[0;38m%s\e[m\":\"\e[0;36m%s\e[m\" }\n\n" "$_key_description" "$_key_id" ""

      # Print with key value.
      else

        if [[ "$_key_id" == "web" ]] ; then

          printf "\n  Description: %s\n" "$_key_description"

          for i in "${_web_stack[@]}" ; do

            printf "  { \"\e[0;38m%s\e[m\":\"\e[0;36m%s\e[m\" }\n" "$_key_id" "$i"

          done

          printf "\n"

        elif [[ "$_key_id" == "db" ]] ; then

          printf "\n  Description: %s\n" "$_key_description"

          for i in "${_db_stack[@]}" ; do

            printf "  { \"\e[0;38m%s\e[m\":\"\e[0;36m%s\e[m\" }\n" "$_key_id" "$i"

          done

          printf "\n"

        else

          printf "\n  Description: %s\n  { \"\e[0;38m%s\e[m\":\"\e[0;36m%s\e[m\" }\n\n" "$_key_description" "$_key_id" "$_i"

        fi

      fi

    fi

  done

  return $_STATE

}
